GRANT CREATE TABLESPACE TO BAVCORE;
ALTER USER BAVCORE QUOTA UNLIMITED ON T1;
ALTER USER BAVCORE QUOTA UNLIMITED ON T2;
ALTER USER BAVCORE QUOTA UNLIMITED ON T3;
ALTER USER BAVCORE QUOTA UNLIMITED ON T4;

CREATE TABLESPACE T1
DATAFILE 'D:\5sem\BD\LB\Lb16\T1.DAT'
SIZE 10M
REUSE AUTOEXTEND 
ON NEXT 2M
MAXSIZE 20M;

CREATE TABLESPACE T2
DATAFILE 'D:\5sem\BD\LB\Lb16\T2.DAT'
SIZE 10M
REUSE AUTOEXTEND
ON NEXT 2M
MAXSIZE 20M;

CREATE TABLESPACE T3 
DATAFILE 'D:\5sem\BD\LB\Lb16\T3.DAT'
SIZE 10M
REUSE AUTOEXTEND
ON NEXT 2M
MAXSIZE 20M;


CREATE TABLESPACE T4
DATAFILE 'D:\5sem\BD\LB\Lb16\T4.DAT'
SIZE 10M 
REUSE AUTOEXTEND 
ON NEXT 2M MAXSIZE 20M;

CREATE TABLE T_RANGE( ID NUMBER, TIME_ID DATE)
PARTITION BY RANGE(ID)
(
  PARTITION p1 VALUES LESS THAN (100) TABLESPACE T1,
  PARTITION p2 VALUES LESS THAN (200) TABLESPACE T2,
  PARTITION p3 VALUES LESS THAN (300) TABLESPACE T3,
  PARTITION pmax VALUES LESS THAN (maxvalue) TABLESPACE T4
);

INSERT INTO T_RANGE(ID, TIME_ID)
VALUES(50,'01-02-2018');

INSERT INTO T_RANGE(ID, TIME_ID)
VALUES(105,'01-02-2017');

INSERT INTO T_RANGE(ID, TIME_ID)
VALUES(205,'01-02-2016');

INSERT INTO T_RANGE(ID, TIME_ID)
VALUES(305,'01-02-2015');

INSERT INTO T_RANGE(ID, TIME_ID)
VALUES(405,'01-02-2015');

SELECT * FROM T_RANGE;

SELECT * FROM T_RANGE PARTITION(p1);

SELECT * FROM T_RANGE PARTITION(p2);

SELECT * FROM T_RANGE PARTITION(p3);

SELECT * FROM T_RANGE PARTITION(pmax);


CREATE TABLE T_INTERVAL(ID number, TIME_ID date)
  PARTITION BY RANGE(TIME_ID)
  INTERVAL (numtoyminterval(1,'month'))
  (
  PARTITION p0 VALUES LESS THAN  (TO_DATE('1-12-2009', 'dd-mm-yyyy')),
  PARTITION p1 VALUES LESS THAN  (TO_DATE ('1-12-2015', 'dd-mm-yyyy')),
  PARTITION p2 VALUES LESS THAN  (TO_DATE ('1-12-2018', 'dd-mm-yyyy'))
  );
SELECT * FROM T_INTERVAL PARTITION(p0);
SELECT * FROM T_INTERVAL PARTITION(p1);
SELECT * FROM T_INTERVAL PARTITION(p2);

--insert into partition with system name sys_p1778
SELECT * FROM T_INTERVAL PARTITION(SYS_P1778);
SELECT * FROM ALL_TAB_PARTITIONS;

INSERT INTO T_INTERVAL(ID, TIME_ID)
VALUES(50,'01-02-2008');

INSERT INTO T_INTERVAL(ID, TIME_ID)
VALUES(105,'01-01-2009');

INSERT INTO T_INTERVAL(ID, TIME_ID)
VALUES(105,'01-01-2014');

ALTER DATABASE 
DATAFILE 'D:\5sem\BD\LB\Lb2\TS_BAV.DBF' 
RESIZE 3000M;

INSERT INTO T_INTERVAL(ID, TIME_ID)
VALUES(205,'01-01-2015');

INSERT INTO T_INTERVAL(ID, TIME_ID)
VALUES(305,'01-01-2016');

INSERT INTO T_INTERVAL(ID, TIME_ID)
VALUES(405,'01-01-2018');

INSERT INTO T_INTERVAL(ID, TIME_ID)
VALUES(505,'01-01-2019');

SELECT * FROM T_INTERVAL partition(p0);

SELECT * FROM T_INTERVAL partition(p1);

SELECT * FROM T_INTERVAL partition(p2);

ALTER DATABASE 
DATAFILE 'D:\5sem\BD\LB\Lb16\T4.DAT' 
RESIZE 30M;

ALTER DATABASE 
DATAFILE 'D:\5sem\BD\LB\Lb16\T2.DAT' 
RESIZE 30M;

ALTER DATABASE 
DATAFILE 'D:\5sem\BD\LB\Lb16\T1.DAT' 
RESIZE 30M;

ALTER DATABASE 
DATAFILE 'D:\5sem\BD\LB\Lb16\T3.DAT' 
RESIZE 30M;


CREATE TABLE T_HASH (STR VARCHAR2 (50), ID NUMBER)
PARTITION BY HASH (str)
(PARTITION k1 TABLESPACE t1,
PARTITION k2 TABLESPACE t2,
PARTITION k3 TABLESPACE t3,
PARTITION k4 TABLESPACE t4
);

INSERT INTO T_HASH (str,id)
VALUES('jjj', 1);

INSERT INTO T_HASH (str,id)
VALUES('gxdghghffdh', 2);

INSERT INTO T_HASH (str,id)
VALUES('AAA', 3);

INSERT INTO T_HASH (str,id)
VALUES('oiouuuoiu', 4);

INSERT INTO T_HASH (str,id)
VALUES('a', 7);

SELECT * FROM T_HASH partitions;

SELECT * FROM T_HASH PARTITION(k1);

SELECT * FROM T_HASH PARTITION(k2);

SELECT * FROM T_hash PARTITION(k3);

SELECT * FROM T_HASH PARTITION(k4);


CREATE TABLE T_LIST(obj char(3))
PARTITION BY LIST (obj)
(
PARTITION p1 VALUES ('a'),
PARTITION p2 VALUES ('b'),
PARTITION p3 VALUES ('c')
);
INSERT INTO  T_LIST(obj)
VALUES('a' );
INSERT INTO  T_LIST(obj)
VALUES('b' );
INSERT INTO  T_LIST(obj)
VALUES('c' );
--EXCEPTION
INSERT INTO  T_LIST(obj)
VALUES('d' );

SELECT * FROM T_LIST PARTITION (p1);
SELECT * FROM T_LIST PARTITION (p2);
SELECT * FROM T_LIST PARTITION (p3) ;
--only with ENABLE ROW MOVEMENT and without partition 'DEFAULT'
ALTER TABLE T_LIST ENABLE ROW MOVEMENT;

UPDATE T_LIST
SET obj='a' WHERE obj='b';

ALTER TABLE T_RANGE MERGE PARTITIONS
p1, p2 INTO PARTITION p5;
--p1, p2 is deleted at all, p5 is created
SELECT * FROM T_RANGE PARTITION(p5);

CREATE TABLE T_LIST1(obj CHAR(3));

ALTER TABLE T_LIST EXCHANGE PARTITION  p3
WITH TABLE T_LIST1;

SELECT * FROM T_LIST partition p3;
--data transfer from partitiom p3 to T_LIST1 with dropping partiotion
SELECT * FROM T_LIST1;

ALTER DATABASE 
DATAFILE 'D:\5sem\BD\LB\Lb16\T4.DAT'
RESIZE 40M;

ALTER TABLE T_INTERVAL SPLIT PARTITION p2 AT 
(TO_DATE('1-12-2016', 'dd-mm-yyyy')) INTO (PARTITION p6 TABLESPACE t4, PARTITION p5 TABLESPACE t2);

SELECT * FROM T_INTERVAL PARTITION(p5);
