/*1*/
SELECT FILE_NAME, TABLESPACE_NAME,STATUS, MAXBYTES, USER_BYTES FROM DBA_DATA_FILES
UNION
SELECT FILE_NAME, TABLESPACE_NAME,STATUS, MAXBYTES, USER_BYTES FROM DBA_TEMP_FILES;
/*2*/
CREATE TABLESPACE DPA_QDATA
  DATAFILE '\\ORACLE-ой\!Labs\DPA_QDATA.dbf'
  SIZE 10 M
  OFFLINE;
  
ALTER TABLESPACE DPA_QDATA ONLINE;

ALTER USER DPA
QUOTA 2 m ON DPA_QDATA;

--user DPA
CREATE TABLE DPA_T1(id number(15) PRIMARY KEY,
name varchar2(10)) TABLESPACE DPA_QDATA;

INSERT INTO DPA_T1 values(1, 'A');------
INSERT INTO DPA_T1 values(2, 'B');
INSERT INTO DPA_T1 values(3, 'C');
Select * from DPA_T1;

/*3*/
SELECT owner, segment_name, segment_type, tablespace_name, bytes, blocks, buffer_pool
FROM SYSTEM.DBA_SEGMENTS
WHERE tablespace_name='DPA_QDATA';

/*4*/
DROP TABLE DPA_T1;
SELECT * FROM USER_RECYCLEBIN;

/*5*/
FLASHBACK TABLE  DPA_T1 TO BEFORE DROP;

/*6*/
BEGIN
  FOR k IN 4..10004
  LOOP
    INSERT INTO DPA_T1 VALUES(k, 'A');
  END LOOP;
  COMMIT;
END;

/*7*/
SELECT * FROM DBA_EXTENTS
WHERE TABLESPACE_NAME='DPA_QDATA';

/*8*/
DROP TABLESPACE DPA_QDATA INCLUDING CONTENTS AND DATAFILES;

/*9*/
SELECT group#, sequence#, bytes, members, status, first_change# FROM V$LOG;

/*10*/
SELECT * FROM V$LOGFILE;

/*11*/
ALTER SYSTEM SWITCH LOGFILE;

/*12*/
ALTER DATABASE ADD LOGFILE GROUP 4 '\\ORACLE-ой\app\Orcl\oradata\orcl\REDO04.LOG'
SIZE 50 m BLOCKSIZE 512;
ALTER DATABASE ADD LOGFILE MEMBER '\\ORACLE-ой\app\Orcl\oradata\orcl\REDO041.LOG' TO GROUP 4;
ALTER DATABASE ADD LOGFILE MEMBER '\\ORACLE-ой\app\Orcl\oradata\orcl\REDO042.LOG' TO GROUP 4;

/*13*/
ALTER DATABASE DROP LOGFILE MEMBER '\\ORACLE-ой\app\Orcl\oradata\orcl\REDO042.LOG';
ALTER DATABASE DROP LOGFILE MEMBER '\\ORACLE-ой\app\Orcl\oradata\orcl\REDO041.LOG';

ALTER DATABASE DROP LOGFILE GROUP 4;

/*14*/
SELECT NAME, LOG_MODE FROM V$DATABASE;
SELECT INSTANCE_NAME, ARCHIVER, ACTIVE_STATE FROM V$INSTANCE;


/*15*/
SELECT * FROM V$ARCHIVED_LOG;
SELECT NAME, FIRST_CHANGE#, NEXT_CHANGE# FROM V$ARCHIVED_LOG;

ARCHIVE LOG LIST; /**************/
SHOW PARAMETER DB_RECOVERY;

/************archive off*********************/
/*19*/
SELECT NAME FROM V$CONTROLFILE;

/*20*/ 
show parameter control;
SELECT * FROM V$CONTROLFILE;

/*----20*/
select name, description from v$parameter;

/*21*/
show parameter spfile;

/*22*/
CREATE PFILE = 'DPA_PFILE.ora' FROM SPFILE;
/*   C:\app\Orcl\product\12.1.0\dbhome_1\database   */

CREATE SPFILE ='SPFILEORCL1.ora' FROM PFILE='DPA_PFILE.ora';

/*23*/
SELECT * FROM V$PWFILE_USERS;

/*24*/
SELECT * FROM V$DIAG_INFO;

/*25*/
/*   C:\app\Orcl\diag\rdbms\orcl\orcl\alert   */

