SET serveroutput ON;

ALTER TABLE TEACHER
ADD BIRTHDAY DATE;

ALTER TABLE TEACHER
ADD SALARY NUMBER(6,2);

SELECT * FROM TEACHER;
describe teacher;

ALTER TABLE TEACHER
DROP COLUMN SALARY;

UPDATE TEACHER
SET BIRTHDAY='12.07.1999', SALARY=123.4, TEACHER_NAME = 'Петрова Марья Петровна'
WHERE TEACHER=6;

UPDATE TEACHER
SET BIRTHDAY='12.12.1999', SALARY=345.4, TEACHER_NAME = 'Иванова Марья Ивановна'
WHERE TEACHER=7;

UPDATE TEACHER
SET BIRTHDAY='12.11.1999',SALARY=3545.43, TEACHER_NAME = 'Павлова Ия Александровна'
WHERE TEACHER=8;

UPDATE TEACHER
SET BIRTHDAY='12.07.1999', SALARY=4333.4, TEACHER_NAME = 'Александрова Марья Валерьевна'
WHERE TEACHER=9;

SELECT regexp_substr(TEACHER_NAME,'(\S+)',1, 1)||' '||
      SUBSTR(regexp_substr(TEACHER_NAME,'(\S+)',1, 2),1, 1)||'. '||
      SUBSTR(regexp_substr(TEACHER_NAME,'(\S+)',1, 3),1, 1)||'. ' as name
FROM TEACHER;

SELECT *
FROM TEACHER
WHERE to_char(to_date(BIRTHDAY), 'DAY')='ПОНЕДЕЛЬНИК';

CREATE VIEW teachBirthNextMonth AS
SELECT *
FROM TEACHER
WHERE to_char(sysdate,'mm')+1 = to_char(BIRTHDAY, 'mm');

CREATE VIEW teachBirthMonths AS
SELECT COUNT(*) FROM TEACHER
GROUP BY to_char(BIRTHDAY, 'mm');

CURSOR teacherBirtday(TEACHER%ROWTYPE) 
		RETURN TEACHER%ROWTYPE IS
		SELECT * FROM TEACHER WHERE MOD((to_char(sysdate,'yyyy') - to_char(BIRTHDAY, 'yyyy')+1), 5)=0;
    
SELECT *  FROM TEACHER;

CURSOR tAvgSalary(TEACHER.SALARY%TYPE,TEACHER.PULPIT%TYPE) 
  RETURN TEACHER.SALARY%TYPE,TEACHER.PULPIT%TYPE  IS
    SELECT FLOOR(AVG(SALARY)), PULPIT
    FROM TEACHER
    GROUP BY PULPIT;
    
SELECT round(AVG(T.SALARY),3), P.FACULTY
FROM TEACHER T
INNER JOIN PULPIT P
ON T.PULPIT = P.PULPIT
GROUP BY P.FACULTY;


SELECT round(AVG(SALARY),3) FROM TEACHER;

DECLARE
  TYPE PERSON IS RECORD
    (
      CODE NUMBER,
      NAME NVARCHAR2(50)
    );
  rec2 PERSON;
BEGIN
  SELECT TEACHER, TEACHER_NAME INTO rec2
  FROM TEACHER
  WHERE TEACHER=8;
  DBMS_OUTPUT.PUT_LINE(rec2.CODE||' '||rec2.NAME);
END;

DECLARE
    TYPE ADDRESS IS RECORD
    (
      TOWN NVARCHAR2(20),
      COUNTRY NVARCHAR2(20)
    );
    TYPE PERSON IS RECORD
    (
      CODE TEACHER.TEACHER%TYPE,
      NAME TEACHER.TEACHER_NAME%TYPE,
      homeAddress ADDRESS
    );
  per1 PERSON;
  per2 PERSON;
BEGIN
  SELECT TEACHER, TEACHER_NAME INTO per1.CODE, per1.NAME
  FROM TEACHER
  WHERE TEACHER=8;
  per1.homeAddress.TOWN := 'Polotsk';
  per1.homeAddress.COUNTRY := 'Belarus';
  per2 := per1;
  DBMS_OUTPUT.PUT_LINE(per2.CODE||' '||per2.NAME||' FROM '||per2.homeAddress.TOWN||' '||per2.homeAddress.COUNTRY);
END;
